#### 전처리된 데이터 파일 로딩

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
X_train = pd.read_csv("./data/salary/preprocessing_X_train5.csv",
                     index_col='no')
X_train.head()

,age,education-num,capital-gain,capital-loss,hours-per-week,workclass_ Federal-gov,workclass_ Self-emp-inc,marital-status_ Married-AF-spouse,marital-status_ Married-civ-spouse,occupation_ ?,...,native-country_ Poland,native-country_ Portugal,native-country_ Puerto-Rico,native-country_ Scotland,native-country_ South,native-country_ Taiwan,native-country_ Thailand,native-country_ Trinadad&Tobago,native-country_ Vietnam,native-country_ Yugoslavia
no,,,,,,,,,,,,,,,,,,,,,
349,66,16,20051,0,35,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2158,32,10,0,0,38,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17884,21,9,0,2001,25,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10086,45,9,0,0,50,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24131,31,11,0,0,40,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
X_test = pd.read_csv("./data/salary/preprocessing_X_test5.csv",
                     index_col='no')
X_test.head()

,age,capital-gain,capital-loss,education-num,education_ 10th,education_ 11th,education_ 12th,education_ 1st-4th,education_ 5th-6th,education_ 7th-8th,...,workclass_ Federal-gov,workclass_ Local-gov,workclass_ Never-worked,workclass_ Private,workclass_ Self-emp-inc,workclass_ Self-emp-not-inc,workclass_ State-gov,workclass_ Without-pay,workclass_ private,native-country_ Holand-Netherlands
no,,,,,,,,,,,,,,,,,,,,,
29306,18,0,0,10,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
29307,29,0,0,9,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
29308,45,0,0,13,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
29309,42,0,0,13,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
29310,41,0,1902,16,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [13]:
X_test.shape,X_train.shape

((19537, 70), (23444, 70))

In [12]:
X_test = X_test[['age','education-num','capital-gain','capital-loss','hours-per-week','workclass_ Federal-gov',
 'workclass_ Self-emp-inc','marital-status_ Married-AF-spouse','marital-status_ Married-civ-spouse','occupation_ ?',
 'occupation_ Adm-clerical','occupation_ Armed-Forces','occupation_ Exec-managerial','occupation_ Farming-fishing',
 'occupation_ Handlers-cleaners','occupation_ Machine-op-inspct','occupation_ Other-service','occupation_ Priv-house-serv','occupation_ Prof-specialty',
 'occupation_ Protective-serv','relationship_ Husband','relationship_ Not-in-family',
 'relationship_ Other-relative','relationship_ Other-relative','relationship_ Own-child',
 'relationship_ Unmarried','relationship_ Wife','race_ Amer-Indian-Eskimo','race_ Black','race_ Other','sex_ Female','sex_ Male','native-country_ Cambodia',
 'native-country_ Canada','native-country_ Columbia','native-country_ Dominican-Republic','native-country_ Dominican-Republic','native-country_ Ecuador',
 'native-country_ El-Salvador','native-country_ England','native-country_ France','native-country_ Germany','native-country_ Greece','native-country_ Guatemala',
 'native-country_ Haiti','native-country_ Holand-Netherlands','native-country_ Honduras','native-country_ Hungary','native-country_ India','native-country_ Iran',
 'native-country_ Ireland','native-country_ Italy','native-country_ Jamaica','native-country_ Japan','native-country_ Laos','native-country_ Mexico','native-country_ Nicaragua',
 'native-country_ Outlying-US(Guam-USVI-etc)','native-country_ Peru','native-country_ Philippines','native-country_ Poland','native-country_ Portugal','native-country_ Puerto-Rico',
 'native-country_ Scotland','native-country_ South','native-country_ Taiwan','native-country_ Thailand','native-country_ Trinadad&Tobago','native-country_ Vietnam','native-country_ Yugoslavia']]

In [5]:
y_train = pd.read_csv("./data/salary/y_train5.csv",
                     index_col='no')
y_train.head()

       income
no
349         1
2158        0
17884       0
10086       1
24131       0

### 목표
- 앙상블 모델의 개념을 이해
- 교차검증에 대한 이해
- GridSearch(최적화를 도와줌)를 이용한 하이퍼파라미터 튜닝 실습

#### 앙상블
- 단일 모델로 예측한 결과보다 더 좋은 성능을 내기위해 여러 모델을 묶어서 예측해보는 기법
- 앙상블 기법
    1. 보팅(Voting)
        - 서로다른 알고리즘의 모델을 학습시켜 예측결과를 투표하는 방법
        - 앙상블의 가장 기본 원리
        - 하드보팅(결과로 투포)과 소프트보팅(평균으로 결정)으로 나뉜다.
    2. 배깅(Bagging)
        - 같은 알고리즘을 가진 모델을 학습시켜 예측결과를 투표하는 방법
        - 학습데이터를 모델마다 다르게 준비(부트스트래핑)
        - 학습에 사용되는 컬럼을 다르게 랜덤선택
        - tree기반의 배깅모델 -> 랜덤포레스트
        - 병렬학습을 해서 상대적으로 속도가 빠르다.
    3. 부스팅(Boosting)
        - 같은 알고리즘을 가진 모델을 학습시켜 예측결과를 투표하는 방법
        - 이전 모델이 잘못 예측한 부분을 다음 모델이 강조해서 학습하는 방법사용
        - 순차적인 학습을 하기때문에 속도가 느리다.

#### 배깅모델

In [6]:
from sklearn.ensemble import RandomForestClassifier

In [7]:
rf_model = RandomForestClassifier(random_state=8, # 랜덤 수 고정
                                 n_estimators=1000, # 앙상블할 모델의 갯수 
                                 max_features=0.6, # 학습에 사용할 특성 수
                                 max_depth=9) # 트리의 깊이 설정

In [8]:
rf_model.fit(X_train,y_train)

C:\Users\pipi1\AppData\Local\Temp\ipykernel_15500\764246711.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf_model.fit(X_train,y_train)

RandomForestClassifier(max_depth=9, max_features=0.6, n_estimators=1000,
                       random_state=8)

In [14]:
rf_pre = rf_model.predict(X_test)

c:\Users\pipi1\anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names seen at fit time, yet now missing:
- native-country_ Dominican-Republic.1
- relationship_ Other-relative.1

  warnings.warn(message, FutureWarning)

In [ ]:
# 결과 업로드
submission = pd.read_csv("./data/salary/sample_submission.csv")
submission["income"] = rf_pre
submission.to_csv("./data/salary/rf_prediction1.csv",
                 index=False)

##XGBBOOST

```
# 코드로 형식 지정됨
```

In [ ]:
X_train.shape

(29305, 88)

In [ ]:
y_train.shape

(29305, 1)

In [ ]:
X_test.shape

(19537, 88)

In [ ]:
X_train.sort_index(axis=1,inplace=True)
X_test.sort_index(axis=1,inplace=True)

In [ ]:
from xgboost import XGBClassifier

In [ ]:
xgb_model = XGBClassifier()

In [ ]:
xgb_model.fit(X_train,y_train)
pre_xgb = xgb_model.predict(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
pre_xgb

array([0, 0, 1, ..., 1, 0, 0])

In [ ]:
test_y_pred = xgb_model.predict(X_test)

In [ ]:
X_test.head()

,age,capital-gain,capital-loss,education-num,hours-per-week,marital-status_ Divorced,marital-status_ Divorced.1,marital-status_ Married-AF-spouse,marital-status_ Married-AF-spouse.1,marital-status_ Married-civ-spouse,...,race_ Other,race_ White,relationship_ Husband,relationship_ Not-in-family,relationship_ Other-relative,relationship_ Own-child,relationship_ Unmarried,relationship_ Wife,sex_ Female,sex_ Male
no,,,,,,,,,,,,,,,,,,,,,
29306,18,0,0,10,16,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,1
29307,29,0,0,9,40,0,0,0,0,1,...,0,1,0,0,0,0,0,1,1,0
29308,45,0,0,13,40,0,0,0,0,1,...,0,0,1,0,0,0,0,0,0,1
29309,42,0,0,13,40,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,1
29310,41,0,1902,16,40,0,0,0,0,1,...,0,1,0,0,0,0,0,1,1,0

In [ ]:
test_id_idx = X_test.index
test_id_idx

Int64Index([29306, 29307, 29308, 29309, 29310, 29311, 29312, 29313, 29314,
            29315,
            ...
            48833, 48834, 48835, 48836, 48837, 48838, 48839, 48840, 48841,
            48842],
           dtype='int64', name='no', length=19537)

In [ ]:
id_pred_df = pd.DataFrame()
id_pred_df['no'] = test_id_idx
id_pred_df['income'] = test_y_pred

id_pred_df

          no  income
0      29306       0
1      29307       0
2      29308       1
3      29309       1
4      29310       1
...      ...     ...
19532  48838       0
19533  48839       0
19534  48840       1
19535  48841       0
19536  48842       0

[19537 rows x 2 columns]

In [ ]:
id_pred_df.to_csv("./data/salary/sample_submission1.csv", index = False)

##SVM

In [ ]:
from sklearn.svm import SVC

In [ ]:
svm_clf = SVC()
svm_clf.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVC()

In [ ]:
test_y_pred_svm = svm_clf.predict(X_test)

In [ ]:
id_pred_df_svm = pd.DataFrame()
id_pred_df_svm['no'] = test_id_idx
id_pred_df_svm['income'] = test_y_pred_svm

id_pred_df_svm

          no  income
0      29306       0
1      29307       0
2      29308       0
3      29309       0
4      29310       1
...      ...     ...
19532  48838       0
19533  48839       0
19534  48840       0
19535  48841       0
19536  48842       0

[19537 rows x 2 columns]

In [ ]:
id_pred_df_svm.to_csv("./data/salary/sample_submission2.csv", index = False)

##Randomforestclassifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf_clf = RandomForestClassifier(n_estimators=5, random_state=0)

In [ ]:
rf_clf.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.

RandomForestClassifier(n_estimators=5, random_state=0)

In [ ]:
test_y_pred_rf = rf_clf.predict(X_test)

In [ ]:
id_pred_df_rf = pd.DataFrame()
id_pred_df_rf['no'] = test_id_idx
id_pred_df_rf['income'] = test_y_pred_rf

id_pred_df_rf

          no  income
0      29306       0
1      29307       0
2      29308       1
3      29309       1
4      29310       1
...      ...     ...
19532  48838       0
19533  48839       0
19534  48840       0
19535  48841       0
19536  48842       0

[19537 rows x 2 columns]

In [ ]:
id_pred_df_rf.to_csv("./data/salary/sample_submission3.csv", index = False)

#### 교차검증
- 모델의 일반화를 위해서 데이터를 훈련, 검증, 평가 셋으로 분리
- 검증셋이 여러개 있어서 모델의 신뢰도를 확보 할 수 있으면 좋다.
- 하지만 데이터양이 충분하지 않은 경우가 많아서 교차검증 기법을 많이 사용
- 교차검증 기법중에서도 k-fold cross validation기법이 일반적으로 쓰임

In [ ]:
from sklearn.model_selection import cross_val_score
cross_score = cross_val_score(rf_model,X_train,y_train,cv=5)

C:\Users\pipi1\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\pipi1\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\pipi1\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\pipi1\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\pipi1\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)

In [ ]:
cross_score.mean()

0.8192894356914193

#### GridSearch를 이용한 모델최적화(하이퍼파라미터튜닝)
- 특정 검증데이터에서만 좋은 하이퍼파라미터보다는 
- 여러 검증데이터에서 좋은 하이퍼파라미터를 선택하는게 일반화에 도움이 되기 떄문에 모델최적화에서도 교차검증을 적용해서 사용한다.

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
# 모델 최적화(하이퍼파라미터튜닝)를 할 객체 생성
model2 = RandomForestClassifier(random_state=0)
# 파라미터 조합
pram_grid = {
    'max_depth' : [5, 10, 15, 20],
    'n_estimators' : [500, 1000, 1500, 2000],
    'max_features' : [0.5, 0.7, 0.8]
}  # 총 4x4x3 개

In [ ]:
grid = GridSearchCV(model2,   #튜닝할 모델
                    pram_grid, # 튜닝해볼 파라미터 조합
                    cv=3, # 교차검증 횟수
                    n_jobs=-1)  # 연산에 사용할 pc코어 수(-1 = 모든 피씨의 연산을 여기에 집중시키겠다)
                    # 총 파라미터 조합갯수 x 교차검증횟수(cv)

In [ ]:
grid.fit(X_train,y_train)

C:\Users\pipi1\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:926: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)

GridSearchCV(cv=3, estimator=RandomForestClassifier(random_state=926),
             n_jobs=-1,
             param_grid={'max_depth': [5, 10, 15, 20],
                         'max_features': [0.5, 0.7, 0.8],
                         'n_estimators': [500, 1000, 1500, 2000]})

In [ ]:
print("최고 점수",grid.best_score_)
print("최고 조합",grid.best_params_)

최고 점수 0.8395061728395062
최고 조합 {'max_depth': 5, 'max_features': 0.8, 'n_estimators': 2000}

In [ ]:
# 학습이 완료된 최고 조합 모델
best_rf = grid.best_estimator_

In [ ]:
pre_test=best_rf.predict(X_test)

In [ ]:
# 결과 업로드
submission = pd.read_csv("./data/salary/sample_submission.csv")
submission["income"] = pre_test
submission.to_csv("./data/salary/rf_prediction2.csv",
                 index=False)

#### 부스팅 모델

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
gbtree = GradientBoostingClassifier(n_estimators=100, # 나무의 갯수, 순차적으로 나무가 100번 만들어짐
                                    learning_rate=0.1, # 다음 트리에 반영할 오차 정도, 이전 트리에서 잘못한것을 다음트리한테 얼마나 반영할건지(0.1= 10%만 반영)
                                    max_depth=5, #나무의 최대깊이
                                    subsample=1 #학슴에 사용할 데이터의 비율
                                   )

In [ ]:
gbtree.fit(X_train,y_train)

C:\Users\pipi1\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GradientBoostingClassifier(max_depth=5, subsample=1)

In [ ]:
pre_gb = gbtree.predict(X_test)
# 결과 업로드
submission = pd.read_csv("./data/salary/sample_submission.csv")
submission["income"] = pre_gb
submission.to_csv("./data/salary/gb_prediction2.csv",
                 index=False)

In [ ]:
# 그리드서치 이용한 모델 최적화 실습
# 모델 최적화(하이퍼파라미터튜닝)를 할 객체 생성
gb_model = GradientBoostingClassifier(random_state=0)
# 파라미터 조합
pram_grid = {
    'learning_rate' : [0.01, 0.1, 0.5, 0.8],
    'n_estimators' : [200, 500, 1000, 1500, 2000],
    'max_depth' : [5,7,9],
    'max_features' : [0.5, 0.7, 0.8],
    'subsample' : [0.5,0.7,1.0]
}  # 총 4x5x3x3x3x(cv)3 의 조합

In [ ]:
grid = GridSearchCV(gb_model,   #튜닝할 모델
                    pram_grid, # 튜닝해볼 파라미터 조합
                    cv=3, # 교차검증 횟수
                    n_jobs=-1)  # 연산에 사용할 pc코어 수(-1 = 모든 피씨의 연산을 여기에 집중시키겠다)

In [ ]:
grid.fit(X_train,y_train)

C:\Users\pipi1\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(cv=3, estimator=GradientBoostingClassifier(random_state=0),
             n_jobs=-1,
             param_grid={'learning_rate': [0.01, 0.1, 0.5, 0.8],
                         'max_depth': [5, 7, 9],
                         'max_features': [0.5, 0.7, 0.8],
                         'n_estimators': [200, 500, 1000, 1500, 2000],
                         'subsample': [0.5, 0.7, 1.0]})

In [ ]:
pre_grid = grid.predict(X_test)

In [ ]:
print("최고 점수",grid.best_score_)
print("최고 조합",grid.best_params_)

최고 점수 0.8361391694725029
최고 조합 {'learning_rate': 0.01, 'max_depth': 5, 'max_features': 0.5, 'n_estimators': 500, 'subsample': 0.5}

In [ ]:
# 학습이 완료된 최고 조합 모델
best_rf = grid.best_estimator_
pre_test=best_rf.predict(X_test)

In [ ]:
# 결과 업로드
submission["income"] = pre_grid
submission.to_csv("./data/salary/gb_prediction2.csv",
                 index=False)

#### 외부 부스팅 라이브러리 사용하기
- boosting의 단점을 보완하고 추가 기능들을 탑재한 외부부스팅 라이브러리들이 있다
- ex) wboost, lightGBM, catboost등

In [ ]:
!pip install xgboost  # gpu에서 병렬 연산을 할수 있게 해주는 # 내부는 C나 c++로 되어있는데 겉은 파이썬
!pip install lightgbm

Collecting xgboost
  Downloading xgboost-1.6.2-py3-none-win_amd64.whl (125.4 MB)
Requirement already satisfied: numpy in c:\users\pipi1\anaconda3\lib\site-packages (from xgboost) (1.21.5)
Requirement already satisfied: scipy in c:\users\pipi1\anaconda3\lib\site-packages (from xgboost) (1.7.3)
Installing collected packages: xgboost
Successfully installed xgboost-1.6.2
Collecting lightgbm
  Downloading lightgbm-3.3.2-py3-none-win_amd64.whl (1.0 MB)
Requirement already satisfied: numpy in c:\users\pipi1\anaconda3\lib\site-packages (from lightgbm) (1.21.5)
Requirement already satisfied: scikit-learn!=0.22.0 in c:\users\pipi1\anaconda3\lib\site-packages (from lightgbm) (1.0.2)
Requirement already satisfied: scipy in c:\users\pipi1\anaconda3\lib\site-packages (from lightgbm) (1.7.3)
Requirement already satisfied: wheel in c:\users\pipi1\anaconda3\lib\site-packages (from lightgbm) (0.37.1)
Requirement already satisfied: joblib>=0.11 in c:\users\pipi1\anaconda3\lib\site-packages (from scikit-learn!=0.22.0->lightgbm) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\pipi1\anaconda3\lib\site-packages (from scikit-learn!=0.22.0->lightgbm) (2.2.0)
Installing collected packages: lightgbm
Successfully installed lightgbm-3.3.2

In [ ]:
from xgboost import XGBClassifier

In [ ]:
xgb_model = XGBClassifier(booster="gbtree", #부스팅할 모델 알고리즘 (선형모델 기반으로 하려면 gblinear)
                          learning_rate=0.1, # 학습률
                          max_depth=6, # 나무의 최대깊이
                          gamma=0.2) # 리프노드 분리를 결정하는 파라미터  
                                 # 키우면 모델 단순, 작아지면 모델 복잡

In [ ]:
xgb_model.fit(X_train,y_train)
pre_xgb = xgb_model.predict(X_test)